disabled_rules:
  - comma
  - control_statement
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count

included:
  - Sources

excluded:
  - Carthage
  - Pods

analyzer_rules:
  - explicit_self

force_cast: warning
force_try:
  severity: warning

large_tuple: 3

type_body_length:
  - 300
  - 400

file_length:
  warning: 400
  error: 600

type_name:
  min_length: 4
  max_length:
    warning: 40
    error: 50
  excluded: iPhone

identifier_name:
  min_length:
    error: 3
  excluded:
    - id
    - URL
    - GlobalAPIKey

reporter: "xcode"
